package com.popcornchicken.tindine;

import android.util.Log;

public class Request {

    private static final String TAG = "Request";  // for debugging

    private String mRequestID;  // will be generated by Firebase when adding to database
    private String mRequesterID;  // cannot be modified
    private String mReserverID;  // will be initialized after request is claimed
    private String mRequestState;
    private RequestData mRequestData;

    // Default constructor required for calls to DataSnapshot.getValue(User.class)
    public Request() {

    }

    public Request(String requesterID, RequestData requestData) {
        // generate unique request ID using Firebase
        FirebaseManager firebaseManager = FirebaseManager.getInstance();
        mRequestID = firebaseManager.getNewRequestID();
        mRequesterID = requesterID;
        mRequestState = RequestState.PENDING;
        mRequestData = requestData;
    }

    public Request(String requesterID, RequestData requestData, String requestID) {
        mRequestID = requestID;
        mRequesterID = requesterID;
        mRequestState = RequestState.PENDING;
        mRequestData = requestData;
    }

    public String getRequestID() {
        return mRequestID;
    }

    public String getRequesterID() {
        return mRequesterID;
    }

    public void setRequesterID(String requesterID) {
        mRequesterID = requesterID;
    }

    public String getReserverID() {
        return mReserverID;
    }

    public void setReserverID(String reserverID) {
        mReserverID = reserverID;
    }

    public String getRequestState() {
        return mRequestState;
    }

    public void setRequestState(String requestState) {
        mRequestState = requestState;
    }

    public RequestData getRequestData() {
        return mRequestData;
    }

    public void setRequestData(RequestData requestData) {
        mRequestData = requestData;
    }

}
